go.mod, go.sum, version.json
- Fixes [panic](https://github.com/libp2p/go-libp2p-pubsub/pull/522) when message published two times. (
- Fixes [memory leak](https://github.com/libp2p/go-libp2p-pubsub/pull/528)
=> Update go-libp2p-pubsub to get necessary fixes

find/client/http/dhash_client.go
Rationale is that double hashed client has a larger surface for failure comparing to the regular client. It does multiple network roundtrips as well as a number of decryption operations in order to fullfill a single lookup. We should be striving for returning a consistent result to the user even if some parts of the query might fail. Logging instead of failing will also allow us to do finer grained debugging in dhfind if necessary. The next step will be to enable streaming to reduce time to the first result.
=> Warn instead of failing in double hashed client

apierror/error.go, apierror/error_test.go
When an error such as a 404 occurrs, and it does not have any message in the response body, use the status text instead of creating an empty error. The empty error is confusing and problematic for logging what happened.
=> Fix empty error messages

find/client/http/dhash_client.go, find/client/http/provider_cache.go
* Move provider cache to a separate file
* Make provider cache thread safe so that the double hashed client can be used concurrently
* This optimisation will reduce dhfind latency significantly (at least by a third) as well as will allow to save up on memory
=> Make provider cache threadsafe

announce/message/message.go, announce/message/message_test.go
If new protocols, unknown to the indexer or assigner service, are encoded into multiaddrs in announce messages, then ignore these. This will allow older indexers to accept messages even when newer address types are included.
Fixes issue #29
=> Ignore multiaddrs with unknown protocols

dagsync/httpsync/publisher.go, dagsync/httpsync/publisher_test.go, go.mod
Is this OK? I think I want to use an http publisher but on an existing server. With this I should be able to make a listener and an http server, start the publisher as `pub` with that listener and attach to a `mux.HandleFunc("/some/path", pub.ServeHttp)` for it.
Doing a bit of 🤞 that `httpath` is going to be properly handled in the announcement so the request will come back in on the right path. I haven't followed that logic through to see if it's actually going to work but since `maurl` is being used then I'm hopeful.
Also, is `httpath` something that could be made official?
=> feat(dagsync/httpsync): add NewPublisherForListener w/ existing Listener

dagsync/httpsync/sync.go, dagsync/httpsync/sync_test.go
The entry chunks for which content is not found are skipped by the indexer. In HTTP publisher, non-existing content returns 404. However, the error returned by the syncer does not allow the "content not found" error to bubble up to ingest pipeline. Therefore, the indexer cannot skip such CIDs from HTTP publishers.
In HTTP Syncer check the response status code and if 404 return relevant errors for upstream error handling.
Relates to:
- https://github.com/ipni/storetheindex/issues/1771
=> Return content not found error when HTTP publisher responds with 404

dagsync/subscriber.go, go.mod, go.sum, version.json
If the Subscriber is closed during an explicit Sync, items used by the explicit sync may become invalid. If the events channel is closed and the explicit sync tries to write to it, the a panic will happen.
This is fixed by using a sync.WaitGroup to track the explicit syncs in progress and a synchronized variable to prevent any additional explicit Sync calls during close.
=> Fix panic when Subscriber is closed during explicit Sync

find/client/dhash_client.go, find/client/http/old_client.go, find/client/option.go
Having these two URLs separate might be confusing for users as most of the times they are going to be the same.
=> Move dhstore URL to dhash_client options

dagsync/announce_test.go, dagsync/latestsync.go, dagsync/option.go, dagsync/subscriber.go, dagsync/subscriber_test.go
The package go-libipni/dagsync has some issues surrounding setting and getting the latest sync, because it conflates the ideas of last ad _synced_ and last ad _processed_. It uses this to cause different behavious when syncing an ad chain or an entry chain.
- SyncFinished event is only sent if updating the latest sync, which is what differentiates syncing an ad chain from an entry chain or syncing an ad chain using a selector.
- There is logic and synchronization in dagsync around updating the latest sync, which amounts to no-op because of the latest sync handler set up by storetheindex.
- When dagsync gets the latest sync via the sync handler supplied by storetheindex, it gets the latest ad _processed_, not the latest ad already _synced_. 
This comment from `SetLatestSync` …
=> Track last synced

version.json
While this version technically has breaking changes, those changes are not seen by anything other than storetheindex, and are fairly specific to how storetheindex uses dagsync. So, making this a minor version update.
=> Create a new version

dagsync/subscriber.go, find/model/provider_info.go
- Include last error in provider info
- Generate error event when async sync of ad chain fails.
=> Provider last error

find/client/provider_cache.go, find/client/provider_cache_test.go
The loop responsible for aggregating contextual and chain level extended providers ranges over the values fetched from indexers, passes the values by reference but does not redeclare the value in each iteration.
Redeclare the value to make sure future iterations do not alter the providers already added to slice.
While at it fix similar issues in other places.
=> Fix bug in provider cache aggregation rage loop

pcache/provider_cache.go, pcache/provider_cache_test.go
List did not handle negative cache entries correctly.
- Added unit tests
- Removed unneeded update counter
- Removed unneeded test
=> Fix pcache List with negative cache entries

pcache/http_source.go, pcache/provider_cache.go, pcache/provider_cache_test.go
- Do not log when provider not found a individual source, as this is normal when there are multiple sources.
- Log when provider not found an any source.
=> Log provider not found error correctly.

find/client/client.go, find/client/dhash_client.go, find/model/provider_info.go, ingest/client/client.go, pcache/http_source.go
- Indexers no longer include `IndexCount` in provider information
- If a URL does not have `http` or `https` scheme, return error.
=> Remove IndexCount from provider information

find/client/dhash_client.go, find/client/dhstore_http.go
When a multihash no longer maps to a metadata, because that metadata was deleted, a NotFound error is returned in the HTTP response in the normal dhstore metadata lookup. With dhfind, the FindMetadata is called directly so that NotFound error is not returned and instead nil data is received. When decryption is done on the nil data, this logs the error. No harm is done, since the logic takes the same path as handling a NotFound error, but the error should not be logged as this is a normal occurrance.
This PR fixes this by handling a not found the same whether it comes from an HTTP response or from value returned by direct call.
=> Fix logging "encrypted metadata too short" when metadata no found

rwriter/provider_response_writer.go, rwriter/response_writer.go
json.Encoder.Encode already adds a newline after each record:
https://pkg.go.dev/encoding/json#Encoder.Encode
=> Do not add extra newline after streaming json response

announce/option.go, announce/receiver.go, dagsync/announce_test.go, dagsync/http_test.go, dagsync/legs_test.go, dagsync/option.go, dagsync/subscriber.go, dagsync/subscriber_test.go, dagsync/sync_test.go
It is not always necessary to have an announcement receiver driving the Subscriber, such as when it is used within a CLI to get advertisements on-demand only. Making it optional avoids the setup time and possible unwanted automated behaviors that result from having the announcement receiver enabled.
=> Having `announce.Receiver` is optional for `Subscriber`

ingest/schema/schema.go, ingest/schema/types_test.go
The Raw codec was previously registered by other packages used in projects that depended on go-libipni, so the problem was not previously seen. Now that the codec is not registered by those packages, projects using go-libipni fail with the error:
```
could not choose a decoder: no decoder registered for multicodec code 85 (0x55)
```
when encountering advertisements with CIDs that use `cid.Raw`.  Registering the Raw codec fixes this.
=> Need to register Raw codec to support cid.Raw

announce/receiver.go, announce/receiver_test.go, dagsync/announce_test.go, dagsync/dtsync/syncer_test.go, dagsync/dtsync/util_test.go, dagsync/example_test.go, dagsync/http_test.go, dagsync/legs_test.go, dagsync/p2p/protocol/head/head_test.go, dagsync/subscriber_test.go, dagsync/sync_test.go, dagsync/test/util.go
This allows verification that the correct publisher address is being announced, even when no sync is happening to update provider information.
=> Log addresses that are in announce messages

announce/receiver.go, mautil/mautil.go, mautil/mautil_test.go
If unspecified addresses are included in the announce message, these need to be removed when filtering addresses. Unspecified addresses are [::] or 0.0.0.0.
Rename `mautil.FilterPrivateIPs` to `mautil.FilterPublic`
=> Filter out unspecified addresses when filtering announce addrs

announce/receiver.go, announce/receiver_test.go, dagsync/announce_test.go, dagsync/dtsync/sync.go, dagsync/option.go, dagsync/subscriber.go, dagsync/subscriber_test.go, dagsync/sync_test.go, dagsync/test/util.go
The number of concurrent advertisement chain syncs, started in response to announcements, can be limited by a configurable value. This is necessary when there are many providers that have advertisement chains to sync and syncing them all at the same time would cause memory exhaustion.
Other changes:
- Remove the ability to use an external data-transfer Manager.
- The announce API takes peer.AddrInfo instead of peer.ID and []multiaddr.Multiaddr
Fixes #101
=> Configurable concurrency limit for async syncs

dagsync/dtsync/head/head.go
If the head protocol is not supported, only an error that contains the correct protocol name.
=> Update dtsync head error message

dagsync/ipnisync/sync.go
There was a redundant check to see if data is already present in the linksystem storage. This PR removes it.
=> Remove redundant data retrieval from linksystem

find/client/client.go, find/client/interface.go, find/model/model.go, find/model/model_test.go
- Add FindBatch convenience fuinction
- Define common Finder interface to replace Interface
=> Drop support for FindBatch API

find/client/client.go, find/client/dhash_client.go, find/client/interface.go
The `Client` and `DHashClient` need to return the same response when no results are found. A not-found response is indicated by an empty `FindResponse` and a nil error. A non-nil `FindResponse` is returned in order to preserve compatibility with existing clients that expect a non-nil value.  
Fixes #53
=> Return same not-found response from dh and non-dh clients

find/client/dhash_client.go, find/client/option.go, pcache/provider_cache.go
Supports use cases where provider address information is not needed.
Fixes #122
=> Option for double-hashed lookups to return only metadata

dagsync/subscriber.go, dagsync/sync_test.go
Remove unused addrs from peerstore to prevent addresses that are no longer valid from continuing to be used.
Confirmed this to fix a publisher address that was no longer valid and should have been replaced by a different address.
Fixes #127
Update non-critical log messages to log at debug level.
=> Remove unused addrs from peerstore

dagsync/ipnisync/sync.go, find/client/client.go, find/client/dhstore_http.go, pcache/http_source.go
The find client is not closing the response body when it gets a not found response. This PR fixes that.
=> Fix leak when find client returns not found

dagsync/option.go, ingest/schema/types.go
A general blockhook function is commonly used by clients of this library when segmented syncs are enbled.
=> Add function to create general dagsync blockhook function

dagsync/option.go, dagsync/subscriber.go, dagsync/sync_test.go
There is now a dagsync.Subscriber option to configure the first sync depth for a new provider.
=> Configurable first sync depth

dagsync/ipnisync/sync.go, dagsync/subscriber.go, mautil/mautil.go, mautil/mautil_test.go
Check for empty addrs earlier when instantiating syncer.
Patch fix for v0.5.11.
See #155 for fix on `main`.
=> Fix empty address check in v0.5.11

dagsync/ipnisync/sync.go, dagsync/subscriber.go, mautil/mautil.go, mautil/mautil_test.go
Assert that a there are addresses associated to a remote peer before constructing a syncer.
=> Check for no addrs before constructing syncer

dagsync/dtsync/sync.go, dagsync/dtsync/syncer.go, dagsync/dtsync/syncer_test.go, dagsync/interface.go, dagsync/ipnisync/sync.go, dagsync/subscriber.go, mautil/mautil.go, mautil/mautil_test.go
Reuse sync client unless peer addresses changed
A new sync client was being created for each advertisement that entries were synced for. This was not a problem for plain HTTP since the HTTP client was reused. However for libp2phttp a new namespaced client was created each time. This established another connection between the indexer and the index-provider. Long advertisement chains could eat up all network resources and cause indexing to grind to a halt.
This PR fixes this by reusing each index-provider's sync client to sync advertisement chains and entries chains. A sync client is kept with the index-provider dagsync subscription handler. A new sync client is created only if there is no sync client yet or if the index-provider's addresses have changed.
=> Reuse sync client5x

dagsync/interface.go, dagsync/ipnisync/sync.go, dagsync/subscriber.go, mautil/mautil.go, mautil/mautil_test.go
A new sync client was being created for each advertisement that entries were synced for. This was not a problem for plain HTTP since the HTTP client was reused. However for libp2phttp a new namespaced client was created each time. This established another connection between the indexer and the index-provider. Long advertisement chains could eat up all network resources and cause indexing to grind to a halt.
This PR fixes this by reusing each index-provider's sync client to sync advertisement chains and entries chains. A sync client is kept with the index-provider dagsync subscription handler. A new sync client is created only if there is no sync client yet or if the index-provider's addresses have changed.
=> Reuse sync client unless peer addresses changed

dagsync/ipnisync/publisher_test.go, go.mod, go.sum, maurl/convert.go
Now that http-path is an official par of multiaddr, use it to identify the path portion of an http multiaddr.
Fixes #42
=> Use multiaddr http-path protocol

dagsync/announce_test.go, dagsync/ipnisync/cid_schema_hint.go, dagsync/ipnisync/cid_schema_hint_test.go, dagsync/ipnisync/publisher.go, dagsync/ipnisync/sync.go, dagsync/ipnisync/sync_test.go, dagsync/option.go, dagsync/subscriber.go, dagsync/test/util.go
This optional header, when present, serves as an indication to advertisement publishers what type of data is being requested and is identified by the CID. This may help some publishers more quickly lookup the data.
The publisher, who receives the Ipni-Cid-Schema-Type HTTP header, does not validate the value, because newer values may need to be received by consumer that is using an older version of library.
Implements fix for https://github.com/ipni/storetheindex/issues/2662
=> Include optional Ipni-Cid-Schema-Type HTTP header

dagsync/announce_test.go, dagsync/ipnisync/publisher.go, dagsync/ipnisync/sync.go, dagsync/option.go, dagsync/subscriber.go
Choosing a specific node prototype based on the cid schema hint adds significant code complexity without significant gain.
=> Always use basicnode.Prototype.Any as not prototype.

dagsync/announce_test.go, dagsync/ipnisync/publisher.go, dagsync/ipnisync/sync.go, dagsync/option.go, dagsync/subscriber.go
Choosing a specific node prototype based on the cid schema hint adds significant code complexity without significant gain.
=> Always use basicnode.Prototype.Any as node prototype
